export EDITOR=/bin/nvim
export CITY='Tarpon Springs'
export HISTORY_IGNORE='(bg|fg|c|ls|pwd|history|exit|make*|* --help)'
export PASSWORD_STORE_ENABLE_EXTENSIONS=true
export GPG_TTY=$(tty)
export ZSH=$HOME/.oh-my-zsh
export PATH=$HOME/bin:$PATH
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
