let g:coc_global_extensions = [
    \ 'coc-spell-checker',
    \ 'coc-cspell-dicts',
    \ 'coc-yank',
    \ 'coc-snippets',
    \ 'coc-python',
    \ 'coc-rls',
    \ 'coc-go',
    \ 'coc-json',
    \ 'coc-yaml',
    \ 'coc-css',
    \ 'coc-html',
    \ 'coc-styled-components',
    \ 'coc-tsserver',
    \ ]
