#! /bin/sh


##############
## monitors ##
##############
bspc monitor DP-3 -d i iii v vii ix
bspc monitor DP-0 -d ii iv vi vii x

##############
## settings ##
##############
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

###########
## rules ##
###########
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


##############
## services ##
##############
xss-lock --transfer-sleep-lock -- betterlockscreen -l &

nitrogen --restore &

polybar main &
polybar bspwm-l &
polybar bspwm-r &

sxhkd &
#compton --config ~/.config/compton/compton.conf --backend glx --blur-method \
#    kawase  --blur-background --blur-strength 20 &
