#! /bin/sh

sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-0 -d I III V VII IX
bspc monitor DP-0 -d II IV VIII X

#bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xss-lock --transfer-sleep-lock -- betterlockscreen -l &

nitrogen --restore &

polybar main &

compton --config ~/.config/compton/compton.conf --backend glx --blur-method \
    kawase  --blur-background --blur-strength 20 &

