#! /bin/sh


##############
## monitors ##
##############
bspc monitor DP-0 -d i iii v vii ix
bspc monitor DP-2 -d ii iv vi viii x

##############
## settings ##
##############
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

###########
## rules ##
###########
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


##############
## services ##
##############

xss-lock --transfer-sleep-lock -- betterlockscreen -l &

nitrogen --restore &

pkill polybar
polybar main &
polybar bspwm-l &
polybar bspwm-r &

pkill sxhkd
sxhkd &
wname LG3d
bspc monitor 'DP-2' -g 3440x2150+1920+0
